name: test
on: [ push ]
jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]
        preset: [ default, debug ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build
        shell: bash
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}
      - name: test
        shell: bash
        run: |
          ctest --preset ${{ matrix.preset }}